/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sdcb.Mattermost.DotNetSdk.Client.OpenAPIDateConverter;

namespace Sdcb.Mattermost.DotNetSdk.Model
{
    /// <summary>
    /// ConfigNativeAppSettings
    /// </summary>
    [DataContract]
    public partial class ConfigNativeAppSettings :  IEquatable<ConfigNativeAppSettings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigNativeAppSettings" /> class.
        /// </summary>
        /// <param name="appDownloadLink">appDownloadLink.</param>
        /// <param name="androidAppDownloadLink">androidAppDownloadLink.</param>
        /// <param name="iosAppDownloadLink">iosAppDownloadLink.</param>
        public ConfigNativeAppSettings(string appDownloadLink = default(string), string androidAppDownloadLink = default(string), string iosAppDownloadLink = default(string))
        {
            this.AppDownloadLink = appDownloadLink;
            this.AndroidAppDownloadLink = androidAppDownloadLink;
            this.IosAppDownloadLink = iosAppDownloadLink;
        }
        
        /// <summary>
        /// Gets or Sets AppDownloadLink
        /// </summary>
        [DataMember(Name="AppDownloadLink", EmitDefaultValue=false)]
        public string AppDownloadLink { get; set; }

        /// <summary>
        /// Gets or Sets AndroidAppDownloadLink
        /// </summary>
        [DataMember(Name="AndroidAppDownloadLink", EmitDefaultValue=false)]
        public string AndroidAppDownloadLink { get; set; }

        /// <summary>
        /// Gets or Sets IosAppDownloadLink
        /// </summary>
        [DataMember(Name="IosAppDownloadLink", EmitDefaultValue=false)]
        public string IosAppDownloadLink { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConfigNativeAppSettings {\n");
            sb.Append("  AppDownloadLink: ").Append(AppDownloadLink).Append("\n");
            sb.Append("  AndroidAppDownloadLink: ").Append(AndroidAppDownloadLink).Append("\n");
            sb.Append("  IosAppDownloadLink: ").Append(IosAppDownloadLink).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConfigNativeAppSettings);
        }

        /// <summary>
        /// Returns true if ConfigNativeAppSettings instances are equal
        /// </summary>
        /// <param name="input">Instance of ConfigNativeAppSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConfigNativeAppSettings input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AppDownloadLink == input.AppDownloadLink ||
                    (this.AppDownloadLink != null &&
                    this.AppDownloadLink.Equals(input.AppDownloadLink))
                ) && 
                (
                    this.AndroidAppDownloadLink == input.AndroidAppDownloadLink ||
                    (this.AndroidAppDownloadLink != null &&
                    this.AndroidAppDownloadLink.Equals(input.AndroidAppDownloadLink))
                ) && 
                (
                    this.IosAppDownloadLink == input.IosAppDownloadLink ||
                    (this.IosAppDownloadLink != null &&
                    this.IosAppDownloadLink.Equals(input.IosAppDownloadLink))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AppDownloadLink != null)
                    hashCode = hashCode * 59 + this.AppDownloadLink.GetHashCode();
                if (this.AndroidAppDownloadLink != null)
                    hashCode = hashCode * 59 + this.AndroidAppDownloadLink.GetHashCode();
                if (this.IosAppDownloadLink != null)
                    hashCode = hashCode * 59 + this.IosAppDownloadLink.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
