/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Sdcb.Mattermost.DotNetSdk.Client;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing RolesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RolesApiTests : IDisposable
    {
        private RolesApi instance;

        public RolesApiTests()
        {
            instance = new RolesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RolesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RolesApi
            //Assert.IsType(typeof(RolesApi), instance, "instance is a RolesApi");
        }

        
        /// <summary>
        /// Test RolesNameRoleNameGet
        /// </summary>
        [Fact]
        public void RolesNameRoleNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string roleName = null;
            //var response = instance.RolesNameRoleNameGet(roleName);
            //Assert.IsType<Role> (response, "response is Role");
        }
        
        /// <summary>
        /// Test RolesNamesPost
        /// </summary>
        [Fact]
        public void RolesNamesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> body = null;
            //var response = instance.RolesNamesPost(body);
            //Assert.IsType<List<Role>> (response, "response is List<Role>");
        }
        
        /// <summary>
        /// Test RolesRoleIdGet
        /// </summary>
        [Fact]
        public void RolesRoleIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string roleId = null;
            //var response = instance.RolesRoleIdGet(roleId);
            //Assert.IsType<Role> (response, "response is Role");
        }
        
        /// <summary>
        /// Test RolesRoleIdPatchPut
        /// </summary>
        [Fact]
        public void RolesRoleIdPatchPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string roleId = null;
            //InlineObject57 body = null;
            //var response = instance.RolesRoleIdPatchPut(roleId, body);
            //Assert.IsType<Role> (response, "response is Role");
        }
        
    }

}
