/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing ChannelMember
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelMemberTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChannelMember
        //private ChannelMember instance;

        public ChannelMemberTests()
        {
            // TODO uncomment below to create an instance of ChannelMember
            //instance = new ChannelMember();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChannelMember
        /// </summary>
        [Fact]
        public void ChannelMemberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChannelMember
            //Assert.IsInstanceOfType<ChannelMember> (instance, "variable 'instance' is a ChannelMember");
        }


        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Fact]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'LastViewedAt'
        /// </summary>
        [Fact]
        public void LastViewedAtTest()
        {
            // TODO unit test for the property 'LastViewedAt'
        }
        /// <summary>
        /// Test the property 'MsgCount'
        /// </summary>
        [Fact]
        public void MsgCountTest()
        {
            // TODO unit test for the property 'MsgCount'
        }
        /// <summary>
        /// Test the property 'MentionCount'
        /// </summary>
        [Fact]
        public void MentionCountTest()
        {
            // TODO unit test for the property 'MentionCount'
        }
        /// <summary>
        /// Test the property 'NotifyProps'
        /// </summary>
        [Fact]
        public void NotifyPropsTest()
        {
            // TODO unit test for the property 'NotifyProps'
        }
        /// <summary>
        /// Test the property 'LastUpdateAt'
        /// </summary>
        [Fact]
        public void LastUpdateAtTest()
        {
            // TODO unit test for the property 'LastUpdateAt'
        }

    }

}
