/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing Command
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommandTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Command
        //private Command instance;

        public CommandTests()
        {
            // TODO uncomment below to create an instance of Command
            //instance = new Command();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Command
        /// </summary>
        [Fact]
        public void CommandInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Command
            //Assert.IsInstanceOfType<Command> (instance, "variable 'instance' is a Command");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'CreateAt'
        /// </summary>
        [Fact]
        public void CreateAtTest()
        {
            // TODO unit test for the property 'CreateAt'
        }
        /// <summary>
        /// Test the property 'UpdateAt'
        /// </summary>
        [Fact]
        public void UpdateAtTest()
        {
            // TODO unit test for the property 'UpdateAt'
        }
        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Fact]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }
        /// <summary>
        /// Test the property 'CreatorId'
        /// </summary>
        [Fact]
        public void CreatorIdTest()
        {
            // TODO unit test for the property 'CreatorId'
        }
        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Fact]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'Trigger'
        /// </summary>
        [Fact]
        public void TriggerTest()
        {
            // TODO unit test for the property 'Trigger'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'IconUrl'
        /// </summary>
        [Fact]
        public void IconUrlTest()
        {
            // TODO unit test for the property 'IconUrl'
        }
        /// <summary>
        /// Test the property 'AutoComplete'
        /// </summary>
        [Fact]
        public void AutoCompleteTest()
        {
            // TODO unit test for the property 'AutoComplete'
        }
        /// <summary>
        /// Test the property 'AutoCompleteDesc'
        /// </summary>
        [Fact]
        public void AutoCompleteDescTest()
        {
            // TODO unit test for the property 'AutoCompleteDesc'
        }
        /// <summary>
        /// Test the property 'AutoCompleteHint'
        /// </summary>
        [Fact]
        public void AutoCompleteHintTest()
        {
            // TODO unit test for the property 'AutoCompleteHint'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
