/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing ConfigPasswordSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigPasswordSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigPasswordSettings
        //private ConfigPasswordSettings instance;

        public ConfigPasswordSettingsTests()
        {
            // TODO uncomment below to create an instance of ConfigPasswordSettings
            //instance = new ConfigPasswordSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigPasswordSettings
        /// </summary>
        [Fact]
        public void ConfigPasswordSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConfigPasswordSettings
            //Assert.IsInstanceOfType<ConfigPasswordSettings> (instance, "variable 'instance' is a ConfigPasswordSettings");
        }


        /// <summary>
        /// Test the property 'MinimumLength'
        /// </summary>
        [Fact]
        public void MinimumLengthTest()
        {
            // TODO unit test for the property 'MinimumLength'
        }
        /// <summary>
        /// Test the property 'Lowercase'
        /// </summary>
        [Fact]
        public void LowercaseTest()
        {
            // TODO unit test for the property 'Lowercase'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Uppercase'
        /// </summary>
        [Fact]
        public void UppercaseTest()
        {
            // TODO unit test for the property 'Uppercase'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }

    }

}
