/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing InlineObject44
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject44Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject44
        //private InlineObject44 instance;

        public InlineObject44Tests()
        {
            // TODO uncomment below to create an instance of InlineObject44
            //instance = new InlineObject44();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject44
        /// </summary>
        [Fact]
        public void InlineObject44InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject44
            //Assert.IsInstanceOfType<InlineObject44> (instance, "variable 'instance' is a InlineObject44");
        }


        /// <summary>
        /// Test the property 'IsPinned'
        /// </summary>
        [Fact]
        public void IsPinnedTest()
        {
            // TODO unit test for the property 'IsPinned'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'FileIds'
        /// </summary>
        [Fact]
        public void FileIdsTest()
        {
            // TODO unit test for the property 'FileIds'
        }
        /// <summary>
        /// Test the property 'HasReactions'
        /// </summary>
        [Fact]
        public void HasReactionsTest()
        {
            // TODO unit test for the property 'HasReactions'
        }
        /// <summary>
        /// Test the property 'Props'
        /// </summary>
        [Fact]
        public void PropsTest()
        {
            // TODO unit test for the property 'Props'
        }

    }

}
