/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing InlineObject37
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject37Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject37
        //private InlineObject37 instance;

        public InlineObject37Tests()
        {
            // TODO uncomment below to create an instance of InlineObject37
            //instance = new InlineObject37();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject37
        /// </summary>
        [Fact]
        public void InlineObject37InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject37
            //Assert.IsInstanceOfType<InlineObject37> (instance, "variable 'instance' is a InlineObject37");
        }


        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

    }

}
