/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing InlineObject35
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject35Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject35
        //private InlineObject35 instance;

        public InlineObject35Tests()
        {
            // TODO uncomment below to create an instance of InlineObject35
            //instance = new InlineObject35();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject35
        /// </summary>
        [Fact]
        public void InlineObject35InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject35
            //Assert.IsInstanceOfType<InlineObject35> (instance, "variable 'instance' is a InlineObject35");
        }


        /// <summary>
        /// Test the property 'Term'
        /// </summary>
        [Fact]
        public void TermTest()
        {
            // TODO unit test for the property 'Term'
        }

    }

}
