/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing InlineObject56
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject56Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject56
        //private InlineObject56 instance;

        public InlineObject56Tests()
        {
            // TODO uncomment below to create an instance of InlineObject56
            //instance = new InlineObject56();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject56
        /// </summary>
        [Fact]
        public void InlineObject56InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject56
            //Assert.IsInstanceOfType<InlineObject56> (instance, "variable 'instance' is a InlineObject56");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IconUrl'
        /// </summary>
        [Fact]
        public void IconUrlTest()
        {
            // TODO unit test for the property 'IconUrl'
        }
        /// <summary>
        /// Test the property 'CallbackUrls'
        /// </summary>
        [Fact]
        public void CallbackUrlsTest()
        {
            // TODO unit test for the property 'CallbackUrls'
        }
        /// <summary>
        /// Test the property 'Homepage'
        /// </summary>
        [Fact]
        public void HomepageTest()
        {
            // TODO unit test for the property 'Homepage'
        }
        /// <summary>
        /// Test the property 'IsTrusted'
        /// </summary>
        [Fact]
        public void IsTrustedTest()
        {
            // TODO unit test for the property 'IsTrusted'
        }

    }

}
