/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing InlineObject52
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject52Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject52
        //private InlineObject52 instance;

        public InlineObject52Tests()
        {
            // TODO uncomment below to create an instance of InlineObject52
            //instance = new InlineObject52();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject52
        /// </summary>
        [Fact]
        public void InlineObject52InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject52
            //Assert.IsInstanceOfType<InlineObject52> (instance, "variable 'instance' is a InlineObject52");
        }


        /// <summary>
        /// Test the property 'HookId'
        /// </summary>
        [Fact]
        public void HookIdTest()
        {
            // TODO unit test for the property 'HookId'
        }
        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Fact]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
