/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2004Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004
        //private InlineResponse2004 instance;

        public InlineResponse2004Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2004
            //instance = new InlineResponse2004();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2004
        /// </summary>
        [Fact]
        public void InlineResponse2004InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2004
            //Assert.IsInstanceOfType<InlineResponse2004> (instance, "variable 'instance' is a InlineResponse2004");
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
