/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing InlineObject54
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject54Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject54
        //private InlineObject54 instance;

        public InlineObject54Tests()
        {
            // TODO uncomment below to create an instance of InlineObject54
            //instance = new InlineObject54();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject54
        /// </summary>
        [Fact]
        public void InlineObject54InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject54
            //Assert.IsInstanceOfType<InlineObject54> (instance, "variable 'instance' is a InlineObject54");
        }


        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Fact]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }
        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Fact]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }

    }

}
