/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing OpenGraph
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpenGraphTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpenGraph
        //private OpenGraph instance;

        public OpenGraphTests()
        {
            // TODO uncomment below to create an instance of OpenGraph
            //instance = new OpenGraph();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpenGraph
        /// </summary>
        [Fact]
        public void OpenGraphInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OpenGraph
            //Assert.IsInstanceOfType<OpenGraph> (instance, "variable 'instance' is a OpenGraph");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Determiner'
        /// </summary>
        [Fact]
        public void DeterminerTest()
        {
            // TODO unit test for the property 'Determiner'
        }
        /// <summary>
        /// Test the property 'SiteName'
        /// </summary>
        [Fact]
        public void SiteNameTest()
        {
            // TODO unit test for the property 'SiteName'
        }
        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }
        /// <summary>
        /// Test the property 'LocalesAlternate'
        /// </summary>
        [Fact]
        public void LocalesAlternateTest()
        {
            // TODO unit test for the property 'LocalesAlternate'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'Videos'
        /// </summary>
        [Fact]
        public void VideosTest()
        {
            // TODO unit test for the property 'Videos'
        }
        /// <summary>
        /// Test the property 'Audios'
        /// </summary>
        [Fact]
        public void AudiosTest()
        {
            // TODO unit test for the property 'Audios'
        }
        /// <summary>
        /// Test the property 'Article'
        /// </summary>
        [Fact]
        public void ArticleTest()
        {
            // TODO unit test for the property 'Article'
        }
        /// <summary>
        /// Test the property 'Book'
        /// </summary>
        [Fact]
        public void BookTest()
        {
            // TODO unit test for the property 'Book'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Fact]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }

    }

}
