/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing PostListWithSearchMatches
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostListWithSearchMatchesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostListWithSearchMatches
        //private PostListWithSearchMatches instance;

        public PostListWithSearchMatchesTests()
        {
            // TODO uncomment below to create an instance of PostListWithSearchMatches
            //instance = new PostListWithSearchMatches();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostListWithSearchMatches
        /// </summary>
        [Fact]
        public void PostListWithSearchMatchesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostListWithSearchMatches
            //Assert.IsInstanceOfType<PostListWithSearchMatches> (instance, "variable 'instance' is a PostListWithSearchMatches");
        }


        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Posts'
        /// </summary>
        [Fact]
        public void PostsTest()
        {
            // TODO unit test for the property 'Posts'
        }
        /// <summary>
        /// Test the property 'Matches'
        /// </summary>
        [Fact]
        public void MatchesTest()
        {
            // TODO unit test for the property 'Matches'
        }

    }

}
