/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing PostMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostMetadata
        //private PostMetadata instance;

        public PostMetadataTests()
        {
            // TODO uncomment below to create an instance of PostMetadata
            //instance = new PostMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostMetadata
        /// </summary>
        [Fact]
        public void PostMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostMetadata
            //Assert.IsInstanceOfType<PostMetadata> (instance, "variable 'instance' is a PostMetadata");
        }


        /// <summary>
        /// Test the property 'Embeds'
        /// </summary>
        [Fact]
        public void EmbedsTest()
        {
            // TODO unit test for the property 'Embeds'
        }
        /// <summary>
        /// Test the property 'Emojis'
        /// </summary>
        [Fact]
        public void EmojisTest()
        {
            // TODO unit test for the property 'Emojis'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'Reactions'
        /// </summary>
        [Fact]
        public void ReactionsTest()
        {
            // TODO unit test for the property 'Reactions'
        }

    }

}
