/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing SamlCertificateStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SamlCertificateStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SamlCertificateStatus
        //private SamlCertificateStatus instance;

        public SamlCertificateStatusTests()
        {
            // TODO uncomment below to create an instance of SamlCertificateStatus
            //instance = new SamlCertificateStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SamlCertificateStatus
        /// </summary>
        [Fact]
        public void SamlCertificateStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SamlCertificateStatus
            //Assert.IsInstanceOfType<SamlCertificateStatus> (instance, "variable 'instance' is a SamlCertificateStatus");
        }


        /// <summary>
        /// Test the property 'IdpCertificateFile'
        /// </summary>
        [Fact]
        public void IdpCertificateFileTest()
        {
            // TODO unit test for the property 'IdpCertificateFile'
        }
        /// <summary>
        /// Test the property 'PublicCertificateFile'
        /// </summary>
        [Fact]
        public void PublicCertificateFileTest()
        {
            // TODO unit test for the property 'PublicCertificateFile'
        }
        /// <summary>
        /// Test the property 'PrivateKeyFile'
        /// </summary>
        [Fact]
        public void PrivateKeyFileTest()
        {
            // TODO unit test for the property 'PrivateKeyFile'
        }

    }

}
