/* 
 * Mattermost API Reference
 *
 * There is also a work-in-progress [Postman API reference](https://documenter.getpostman.com/view/4508214/RW8FERUn). 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: feedback@mattermost.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sdcb.Mattermost.DotNetSdk.Api;
using Sdcb.Mattermost.DotNetSdk.Model;
using Sdcb.Mattermost.DotNetSdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sdcb.Mattermost.DotNetSdk.Test
{
    /// <summary>
    ///  Class for testing Team
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Team
        //private Team instance;

        public TeamTests()
        {
            // TODO uncomment below to create an instance of Team
            //instance = new Team();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Team
        /// </summary>
        [Fact]
        public void TeamInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Team
            //Assert.IsInstanceOfType<Team> (instance, "variable 'instance' is a Team");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreateAt'
        /// </summary>
        [Fact]
        public void CreateAtTest()
        {
            // TODO unit test for the property 'CreateAt'
        }
        /// <summary>
        /// Test the property 'UpdateAt'
        /// </summary>
        [Fact]
        public void UpdateAtTest()
        {
            // TODO unit test for the property 'UpdateAt'
        }
        /// <summary>
        /// Test the property 'DeleteAt'
        /// </summary>
        [Fact]
        public void DeleteAtTest()
        {
            // TODO unit test for the property 'DeleteAt'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AllowedDomains'
        /// </summary>
        [Fact]
        public void AllowedDomainsTest()
        {
            // TODO unit test for the property 'AllowedDomains'
        }
        /// <summary>
        /// Test the property 'InviteId'
        /// </summary>
        [Fact]
        public void InviteIdTest()
        {
            // TODO unit test for the property 'InviteId'
        }
        /// <summary>
        /// Test the property 'AllowOpenInvite'
        /// </summary>
        [Fact]
        public void AllowOpenInviteTest()
        {
            // TODO unit test for the property 'AllowOpenInvite'
        }

    }

}
